version: '3'
services:
  casino_db:
    image: mysql:5.7
    environment:
      MYSQL_USER: casino_user
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: mysql_password
    ports:
    - '3316:3306'
    volumes:
    - db-data:/var/lib/mysql

  casino_webapp:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
    - ./:/webapp
    - public-data:/sc_casino/public
    - tmp-data:/sc_casino/tmp
    - log-data:/sc_casino/log
    ports:
    - "80:3000"
    depends_on:
    - casino_db
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: