# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'root_password' } %>
  host: casino_db

development:
  <<: *default
  database: casino_webapp_development

test:
  <<: *default
  database: casino_webapp_test

production:
  <<: *default
  database: db/prowduction.sqlite3
